### ISSUE TITLE
String messes up when apk path has spaces in file path

### ISSUE THREAD

**Issue by EliCDavis** [holmeszyx/goadb#1]
https://github.com/holmeszyx/goadb/blob/dceec9cf0536acf8f8f5423af1c853aad97cc8d8/goadb.go#L234

**Comment by holmeszyx** [comment]
Changed the split func.
Should try update the code which has last commit [b09c762](https://github.com/holmeszyx/goadb/commit/b09c7622480acf43a9e3a9b2999a063b07f52097)
